### ISSUE TITLE
AttributeError exception due to backward incompatible change in Pillow 10.0.0

### ISSUE THREAD

**Issue by Emily3403** [matmair/brother_ql-inventree#33]
This is essentially a copy of [this](https://github.com/pklaus/brother_ql/issues/142) issue of the original `brother_ql` repository.

If Pillow >= 10.0.0 is installed, the program fails with the following stacktrace:
```python
Traceback (most recent call last):
  File "/home/emily/.local/bin/brother_ql", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emily/.local/lib/python3.11/site-packages/brother_ql/cli.py", line 146, in print_cmd
    instructions = convert(qlr=qlr, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emily/.local/lib/python3.11/site-packages/brother_ql/conversion.py", line 113, in convert
    im = im.resize((dots_printable[0], hsize), Image.ANTIALIAS)
                                               ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'

```

As recommended in [this](https://stackoverflow.com/a/76616129) Stackoverflow post, the fix consists of renaming `Image.ANTIALIAS` to `Image.LANCZOS`. 

[This](https://github.com/pklaus/brother_ql/pull/143) Pull Request already makes all the necessary changes for the original repo.

Currently, a fix is to force the old Pillow version with `pip install --force-reinstall -v "Pillow==9.5.0"`, however I'd prefer if I was able to directly install and use the software.

Thanks and cheers in advance 😊

**Comment by bashyftw** [comment]
Im getting the same result using the P900W

**Comment by matmair** [comment]
Hi @Emily3403 I had notitifications of for this repo - no idea why - and did not see this till now.
This was addressed in https://github.com/matmair/brother_ql-inventree/pull/37 so updating the package should solve the issues. Please let me know if this works for you now.

**Comment by Emily3403** [comment]
Seams to work fine, thanks!
